### ISSUE TITLE
Heroku Discover Page: Top 40 button and Search

### ISSUE THREAD

**Issue by dunlapww** [dunlapww/viewing_party#72]
Currently, on Heroku, /discover buttons and links not working.  should return top40 and redirect to results page.

**Comment by katemorris** [comment]
This might be solved by #82

**Comment by katemorris** [comment]
Adding the gem file didn't help. The issue is that the URL of any movie in results is now https://viewing-party-gkw.herokuapp.com/movies/uuid in heroku. It should have the ID where uuid is. Need to update.
